export { default as BreadcrumbIcon } from "./BreadcrumbIcon";
export { default as CloseIcon } from "./CloseIcon";
export { default as InstagramIcon } from "./InstagramIcon";
export { default as TwitterIcon } from "./TwitterIcon";
export { default as LinkedinIcon } from "./LinkedinIcon";
export { default as SimranLogo } from "./SimranLogo";
export { default as SimranLogo_V2 } from "./SimranLogo_V2";
export { default as ModalCloseIcon } from "./ModalCloseIcon";
export { default as DownloadIcon } from "./DownloadIcon";
